version: '3.7'

services:
  chessapp: 
    container_name: chessapp
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 1337:80
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  backend: 
    container_name: backend
    expose:
      - 5000
    build:
      context: .
      dockerfile: DockerfileServer
    volumes:
      - '.:/app'
      - '/app/node_modules' 
    ports:
      - 5000:5000    
  mongo:
    image: 'mongo' 
    command: mongod --port 27021
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=chessapp   
    volumes:
      - ./mongo-volume:/data/db