version: '3.7'

services:
  chessapp: 
    container_name: chessapp
    build:
      context: .
      dockerfile: ${DOCKERFILE_FOR_FRONTEND}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${PRODUCTION_PORT}:${INTERNAL_NGINX_PORT}
    environment:
      - CHOKIDAR_USEPOLLING=true
  backendsocket: 
    container_name: 'backendsocket'
    expose:
      - ${REACT_APP_BACKEND_PORT}
    build:
      context: .
      dockerfile: docker/DockerfileServer
    volumes:
      - '.:/app'
      - '/app/node_modules'  
    ports:
      - "${REACT_APP_BACKEND_PORT}:${REACT_APP_BACKEND_PORT}"
  mongo:
    image: 'mongo' 
    command: "mongod --port ${DBPORT}"
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=${DBNAME}"
    volumes:
      - ./mongo-volume:/data/db