version: '3.7'

services:
  chessapp: 
    container_name: chessapp
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${PRODUCTION_PORT}:80
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend: 
    container_name: backend
    expose:
      - ${BACKEND_PORT}
    build:
      context: .
      dockerfile: DockerfileServer
    volumes:
      - '.:/app'
      - '/app/node_modules' 
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
  mongo:
    image: 'mongo' 
    command: "mongod --port ${DBPORT}"
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=chessapp   
    volumes:
      - ./mongo-volume:/data/db