FROM node:18-alpine3.14 as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY docker/client-package.json ./package.json
# COPY package-lock.json ./

RUN npm install
RUN npm install react-scripts@5.0.1 -g

COPY . ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE ${INTERNAL_NGINX_PORT}
CMD ["nginx", "-g", "daemon off;"]