name: ChessApp Continuous Integration - Docker compose Trial run

on: 
  push: 
    branches:
      - master 

jobs: 
  deploy:      
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with: 
          node-version: 16       
        env:
          REACT_APP_SECRET: ${{ secrets.REACT_APP_SECRET }}     
      - run: npm install
      - run: docker-compose build
      - run: docker-compose up -d
      - run: node .github/workflows/dockerrun.js

